### ISSUE TITLE
try bdiso and get RuntimeError: You do not appear to have entered any MediaInfo data for your video upload.

### ISSUE THREAD

**Issue by ted423** [damonjavert/jps2sm#42]
### Description
RuntimeError: You do not appear to have entered any MediaInfo data for your video upload.
### Expected behaviour
where can I add BDinfo?
Can I add it manual
### Steps to reproduce
```
jps2sm --urls "https://jpopsuki.eu/torrents.php?id=223742&torrentid=313723"
```

**Comment by damonjavert** [comment]
pyunpack (patool/7z) cannot extract BRs so jps2sm cannot parse them.

**Comment by ted423** [comment]
> pyunpack (patool/7z) cannot extract BRs so jps2sm cannot parse them.

so , how to use with BDMV？

**Comment by damonjavert** [comment]
You cannot use jps2sm to transfer BD ISOs as pyunpack does not support them. jps2wm needs to unpack the ISO to inspect it.

An alternative is to have jps2sm mount the ISO, but this would mean jps2sm would need root/elevated access and it may not be very platform independent. See: https://stackoverflow.com/questions/1667257/how-do-i-mount-a-filesystem-using-python

There are not many BR ISO torrents around so it is probably easier to manually upload them. How many BR ISO torrents are you seeding?

**Comment by ted423** [comment]
![image](https://github.com/damonjavert/jps2sm/assets/7042766/804ce44f-0df4-42ce-a631-0ced03a3eaa3)
/dev/sdd1                  11T  9.0T  1.4T   88% /share/Aidol/AKB48

**Comment by ted423** [comment]
I am currently using under win.
manual mount or manually fill bdinfo?
another way is try work with this https://github.com/techmovie/easy-upload/blob/master/README-en.md

**Comment by damonjavert** [comment]
As I said, the manual mount method would require additional code and would likely be a bad idea anyway, especially for such an edge-case. You can submit a PR to do it if you like. Such a feature would need to locate and mount the ISO, then major refactoring of `get_mediainfo()` to support it.

The tool you linked does not support MediaInfo extraction at all: "Most international sites require full MediaInfo data while even some official resources in Chinese sites fail to provide it. In this case, MediaInfo data needs a manual extraction."

So you will need to manually add them. You can msg Staff at SM and they can make your BD ISOs perma-FL. Most torrents >30Gb are FL anyway.

If you need help creating uploads you can ask on Discord or IRC.
